project_id = "ngndjbeltygurjcnlcxz"

[functions.calculate-distance]
verify_jwt = false

[functions.lookup-address]
verify_jwt = false

[functions.wefact]
verify_jwt = false

[functions.generate-delivery-pdf]
verify_jwt = false

[functions.sync-wefact-statuses]
verify_jwt = false