// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngndjbeltygurjcnlcxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nbmRqYmVsdHlndXJqY25sY3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MTA4NDUsImV4cCI6MjA4NzE4Njg0NX0.fhGPHjNCQa0m9EcWmTNNfxr1U6oMPWelBKMuEdE1lKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});